### PR TITLE
fix(utils): unexpected behavior for tail & head

### PR DESCRIPTION
**Pull request by ColinFay**
When passed a character vector, head() and tail() now try to do
a coercion to integer.

### CODE REVIEW

**Comment by bbolker** [comment]
I remember seeing this discussed on some channel (`r-devel`?), but I think this is the wrong place to submit a patch &mdash; this is an unofficial, read-only mirror of the R SVN repository. There is a more official mirror, with instructions about how to submit a patch, [here](https://github.com/r-devel/r-svn#r-svn-ci-tool) .

**Comment by ColinFay** [comment]
Hey @bbolker, thanks, I do indeed know that this is not the right place, I've used this to generate the patch file :)

**Comment by bbolker** [comment]
OK. FWIW you might still find the more-official mirror useful: apparently it will run tests via GitHub Actions etc. as well. (Who knows, maybe someday it will even be opened as an official channel for patches ...)

**Comment by ColinFay** [comment]
Yeah I was unfortunately unable to find back the more-official mirror, despite spending 15 minutes searching github and google, so went back to this one. 

Would you have the link bookmarked by any chance?

**Comment by bbolker** [comment]
https://github.com/r-devel/r-svn#r-svn-ci-tool

**Comment by ColinFay** [comment]
That's super awesome, thanks a lot !

**Pull request closed without merging**
